services:
  client:
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host

  server:
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
